# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Domov
    url: /
    weight: 10
  - name: Učivo
    url: ucivo/
    weight: 20
  - name: Testy
    url: testy/
    weight: 30
  - name: Pracovné listy
    url: pracovne-listy/
    weight: 40
  - name: O projekte
    url: o-projekte/
    weight: 50