# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Domov
    url: /
    weight: 10
  - name: Obsah
    url: obsah/
    weight: 20
  - name: O projekte
    url: o-projekte/
    weight: 30